FROM windj007/jupyter-keras-tools:latest
MAINTAINER Roman Suvorov <rsuvorov@isa.ru>

RUN pip install -U git+https://github.com/hyperopt/hyperopt git+https://github.com/HIPS/Spearmint pymongo networkx
RUN apt-get install -yqq libav-tools
